// <auto-generated />
using System;
using EMS.Core.API.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EMS.Core.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210506103151_DbFix")]
    partial class DbFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EMS.Core.API.Models.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContactType")
                        .HasColumnType("int")
                        .HasColumnName("contactType");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("createdOn");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("personId");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Contacts", "core");
                });

            modelBuilder.Entity("EMS.Core.API.Models.DayOff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("createdOn");

                    b.Property<int>("DayOffType")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<double>("Hours")
                        .HasColumnType("float")
                        .HasColumnName("hours");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit")
                        .HasColumnName("isPaid");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("personId");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("DayOffs", "core");
                });

            modelBuilder.Entity("EMS.Core.API.Models.Holiday", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("createdOn");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("datetime")
                        .HasColumnName("holidayDate");

                    b.Property<DateTime?>("ToDoDate")
                        .HasColumnType("datetime")
                        .HasColumnName("toDoDay");

                    b.HasKey("Id");

                    b.ToTable("Holidays", "core");
                });

            modelBuilder.Entity("EMS.Core.API.Models.MotivationModificator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("createdOn");

                    b.Property<double>("ModValue")
                        .HasColumnType("float")
                        .HasColumnName("modValue");

                    b.Property<long>("StaffId")
                        .HasColumnType("bigint")
                        .HasColumnName("StaffId");

                    b.HasKey("Id");

                    b.ToTable("MotivationModificators", "core");
                });

            modelBuilder.Entity("EMS.Core.API.Models.OtherPayment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("createdOn");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("personId");

                    b.Property<double>("Value")
                        .HasColumnType("float")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("OtherPayments", "core");
                });

            modelBuilder.Entity("EMS.Core.API.Models.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BornedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("bornedOn");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("createdOn");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lastName");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("secondName");

                    b.HasKey("Id");

                    b.ToTable("People", "core");
                });

            modelBuilder.Entity("EMS.Core.API.Models.PersonPhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Base64")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("base64");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("createdOn");

                    b.Property<string>("Mime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mime");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("personId");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonPhotos", "core");
                });

            modelBuilder.Entity("EMS.Core.API.Models.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("createdOn");

                    b.Property<double>("HourRate")
                        .HasColumnType("float")
                        .HasColumnName("hourRate");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("teamId");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Positions", "core");
                });

            modelBuilder.Entity("EMS.Core.API.Models.Staff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("createdOn");

                    b.Property<long>("ManagerId")
                        .HasColumnType("bigint")
                        .HasColumnName("managerId");

                    b.Property<long?>("MotivationModificatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("motivationModId");

                    b.Property<long?>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("personId");

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint")
                        .HasColumnName("positionId");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("MotivationModificatorId")
                        .IsUnique()
                        .HasFilter("[motivationModId] IS NOT NULL");

                    b.HasIndex("PersonId");

                    b.HasIndex("PositionId");

                    b.ToTable("Staff", "core");
                });

            modelBuilder.Entity("EMS.Core.API.Models.Team", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("createdOn");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Teams", "core");
                });

            modelBuilder.Entity("EMS.Core.API.Models.Contact", b =>
                {
                    b.HasOne("EMS.Core.API.Models.Person", "Person")
                        .WithMany("Contacts")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("EMS.Core.API.Models.DayOff", b =>
                {
                    b.HasOne("EMS.Core.API.Models.Person", "Person")
                        .WithMany("DayOff")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("EMS.Core.API.Models.OtherPayment", b =>
                {
                    b.HasOne("EMS.Core.API.Models.Person", "Person")
                        .WithMany("OtherPayments")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("EMS.Core.API.Models.PersonPhoto", b =>
                {
                    b.HasOne("EMS.Core.API.Models.Person", "Person")
                        .WithMany("Photos")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("EMS.Core.API.Models.Position", b =>
                {
                    b.HasOne("EMS.Core.API.Models.Team", "Team")
                        .WithMany("Positions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("EMS.Core.API.Models.Staff", b =>
                {
                    b.HasOne("EMS.Core.API.Models.Person", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMS.Core.API.Models.MotivationModificator", "MotivationModificator")
                        .WithOne("Staff")
                        .HasForeignKey("EMS.Core.API.Models.Staff", "MotivationModificatorId");

                    b.HasOne("EMS.Core.API.Models.Person", "Person")
                        .WithMany("Staff")
                        .HasForeignKey("PersonId");

                    b.HasOne("EMS.Core.API.Models.Position", "Position")
                        .WithMany("Staff")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("MotivationModificator");

                    b.Navigation("Person");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("EMS.Core.API.Models.MotivationModificator", b =>
                {
                    b.Navigation("Staff");
                });

            modelBuilder.Entity("EMS.Core.API.Models.Person", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("DayOff");

                    b.Navigation("OtherPayments");

                    b.Navigation("Photos");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("EMS.Core.API.Models.Position", b =>
                {
                    b.Navigation("Staff");
                });

            modelBuilder.Entity("EMS.Core.API.Models.Team", b =>
                {
                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
