// Root
export const SET_OPERATION_WAITING_FLAG = "SET_OPERATION_WAITING_FLAG";
export const SET_OPERATION_COMPLETE_FLAG = "SET_OPERATION_COMPLETE_FLAG";

// Example module
export const SET_STRING_FIELD = "SET_STRING_FIELD";